
micronaut:
  application:
    name: simple-crud-micronaut-server

postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: simple_crud_db
      user: postgres
      password: root
      maxSize: 5

datasources:
  default:
    url: jdbc:postgresql://localhost/simple_crud_db
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

jpa:
  default:
    packages-to-scan:
      - 'simple.crud.micronaut.server'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'