---
micronaut:
  application:
    name: simple-crud-micronaut-server

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/simple-crud-db"
  cluster:
    maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
