---
micronaut:
  application:
    name: simple-crud-micronaut-server

---
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: simple_crud_db
      user: root
      password: root
      maxSize: 5
